name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Descargas

            ### macOS
            - **Apple Silicon (M1/M2/M3)**: Descarga el archivo `-arm64.dmg`
            - **Intel**: Descarga el archivo `-x64.dmg`

            ### Windows
            - Descarga el archivo `.exe` (instalador) o `-portable.exe` (sin instalación)

            ### Linux
            - **AppImage**: Funciona en todas las distribuciones
            - **DEB**: Para Ubuntu/Debian
            - **RPM**: Para Fedora/RedHat/CentOS

            ## Instalación

            Simplemente descarga el archivo correspondiente a tu sistema operativo y arquitectura.

            ## Características

            - Reproduce YouTube Music en una ventana de escritorio dedicada
            - Mini reproductor con interfaz personalizada
            - Notificaciones de cambio de canción
            - Controles desde el system tray
            - Se minimiza al tray en lugar de cerrar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
